### ISSUE TITLE
Allow VARCHAR key to be unlimited

### ISSUE THREAD

**Issue by abhishiv** [lukechilds/keyv-sql#17]
Hey @lukechilds 

Thanks for the great module!

This issue is aimed specifically for caching long urls.

Right now the key column is `VARCHAR(n)`

```
{
  name: 'key',
  primaryKey: true,
  dataType: `VARCHAR(${Number(this.opts.keySize)})`
}
```

In postgres if you skip `n` in `VARCHAR(n)` it allows unlimited characters, so it might be good to have an option to specify that.

Coming to think about it, why not just make it `TEXT`. I think performance wise it should be the same.

**Comment by lukechilds** [comment]
The reasoning behind the current behaviour is here: https://github.com/lukechilds/keyv-sql/issues/5

Do you have a specific use case where you need large keys and you can't just pass in a higher key size?

>Coming to think about it, why not just make it TEXT. I think performance wise it should be the same.

I don't think using `TEXT` for a primary key is a good idea, you can only specify a `TEXT` index for a certain length so it could lead to duplicate keys and would only be as safe as `VARCHAR(n)` where `n` is the index length.

**Comment by abhishiv** [comment]
Actually when I think about it, I can just create a checksum of a long url, and then use that as a key. 

I'll close this issue.

Thanks!
