### ISSUE TITLE
A VARCHAR(255) key may not work on a default installation of MySQL/MariaDB

### ISSUE THREAD

**Issue by MySidesTheyAreGone** [lukechilds/keyv-sql#5]
I got an error at table creation time and took some time to figure it out.

A default installation of MySQL/MariaDB will have InnoDB storage enabled by default for all tables and will use UTF8 for text e.g. VARCHAR columns. According to the following page:

https://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html

The default restriction on keys is that they shouldn't be longer than 767 bytes. A VARCHAR(255) that uses UTF8 (maximum 4 bytes per char) will - in the worst case - nom nom nom 255*4 = 1020 bytes. That's not going to work. 

If you do a quick test on a real MariaDB instance you'll get an error message at table creation time (blah blah blah maximum key size 767 bytes blah).

But rejoice!!! Since you are the Master of Kyev you get to FIX this problem!!! I will follow suit.

A few suggestions:

 - THE BUREAUCRAT WAY: If the size of 255 chars is important for any reason, you could simply tell the user that he needs to tune MariaDB/MySQL to accept longer keys. I currently do not now if this is actually possible though

 - THE PRAGMATIST WAY: I work in business intelligence and I have never ever had to declare a key larger than 30 chars or so (indeed 30 is already outrageously large). 767 bytes computes down to a VARCHAR(191), which would work for anyone who understands DBs. Redis/MongoDB would remain as they are, of course.

 - THE OVERENGINEERED AS FUCK WAY: To keep a 255 chars key on Postgres and SQLite but reduce it to 191 on MySQL you can remove the key specification from the CREATE TABLE statement in keyv-sql and use different ALTER TABLE statements in keyv-{sqlite,postgres,mysql} after the `super(opts)` returns by redefining `this.query` as `this.query = this.query.then(() => this.query('BLAH BLAH BLAH'))`. On MySQL you can declare a 191 chars index on a 255 chars column so that only the first 191 characters will count and the index will be small enough but the column will still be 255.

There are probably a lot more WAYs but this is all I have right now. Take your time, I'll go with whatever you pick.

**Comment by MySidesTheyAreGone** [comment]
Oh of course you could make the key size configurable. Don't know why I didn't think of this first.

**Comment by lukechilds** [comment]
Good spot. 🔍

I think a key size over 30 is pretty reasonable for unique cache keys. For example an HTTP cache will often implement keys with a pattern like this: `${namespace}:${method}:${scheme + host + uri}`. So `namespace:GET:https://api.foo.com?bar=true` is already 42 chars and that's a pretty simple request.

I think the best solution would  be to have a default of 255 and allow passing a new size as an option. We can then pass 191 to `@keyv/sql` from `@keyv/mysql`. Like you mention in your second comment.

Where do you see the error btw? I don't see anything on my Travis build: https://travis-ci.org/lukechilds/keyv-mysql/jobs/264064491

**Comment by MySidesTheyAreGone** [comment]
No the tests didn't catch anything on my clones either, I got it when I attached my app to a fresh mariadb server, default cfg. When the CREATE TABLE ran I got the error. It mentioned this oddly specific limit and that's how I found everything out. The error went away when I reduced the key to 191 chars.

**Comment by MySidesTheyAreGone** [comment]
If you make the key size configurable, it might be a good idea to set the default to 191 right inside keyv-mysql, just to be on the safe side.

**Comment by lukechilds** [comment]
> it might be a good idea to set the default to 191 right inside keyv-mysql, just to be on the safe side.

👌

**Comment by lukechilds** [comment]
On the MySQL docs you linked it insinuates 255 should be ok. 

> The index key prefix length limit is 767 bytes for InnoDB tables that use the REDUNDANT or COMPACT row format. For example, you might hit this limit with a column prefix index of more than 
 255 characters on a TEXT or VARCHAR column, assuming a utf8mb3 character set and the maximum of 3 bytes for each character.

https://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html

And mentions that it's 3bytes per char.

So is this specific to MariaDB, not MySQL?

**Comment by lukechilds** [comment]
Ah, I think I get it, UTF-8 chars are normally 3 bytes but can potentially be up to 4 bytes?

**Comment by MySidesTheyAreGone** [comment]
utf8mb3 is strange, I'm pretty sure the default is called utf8mb4? Anyway yes, UTF8 is variable size and MariaDB assumes the worst. I'll do more research tomorrow, it's pretty late here.

**Comment by MySidesTheyAreGone** [comment]
Oh it's such a mess, I'm going to bed 

http://mysqlserverteam.com/mysql-8-0-when-to-use-utf8mb3-over-utf8mb4/

**Comment by lukechilds** [comment]
When you get a chance, could you let me know which version of MariaDB you were getting the errors on?

I've tested 10.0, 10.1 and 10.2 and I don't get any errors with `VARCHAR(255)`.

**Comment by MySidesTheyAreGone** [comment]
Locally, it's 10.1.26, Arch Linux:

2017-08-15 11:38:32 - error: STORAGE manager | Received an error from the underlying storage library
Error: Specified key was too long; max key length is 767 bytes

However, I just tested the MariaDB instance running on my Synology NAS, and it works! Version is 10.0.30 and the column's charset after creation is "utf8".

FInally, I reduced the key size to 191 and tested my local instance again. This time it worked, and the charset is, as predicted, "utf8m4".

I think what we're dealing with is on one side defaults that differ between deployments depending on OS or version, and on the other the fundamental uncertainty in determining wether something should be configured at the application level or at the DB level. Because it's not like you can map the entire DB configuration file into Keyv, so what I'd suggest at this point is to make the key size configurable in Kyev, since it does have a direct impact on the index size and the resulting table's performance and you can't change it otherwise, and leave the charset up to the DBA. I wouldn't even drop the default to 191 either, at this point. Just let hoever's acting as DBA sort it out.

**Comment by lukechilds** [comment]
> I wouldn't even drop the default to 191 either, at this point. Just let hoever's acting as DBA sort it out.

I agree, that seems like the best solution. Looks like it works with the default MariaDB stable on Ubuntu so that's good enough for me. I'll maybe mention this in the readme though as it seems like a problem certain envs will definitely have.

Also, I really need to get `@keyv/mysql` tested against both MariaDB and MySQL. Installing them both side by side is proving rather difficult. Any experience with that?

**Comment by MySidesTheyAreGone** [comment]
Yeah it's a nightmare

https://mariadb.com/kb/en/mariadb/installing-mariadb-alongside-mysql/

Since we're on the topic of testing, did you ever at any point stumble on a problem with Maria / MySQL where the JSON would lose all of the backslashes and become un-parseable? If you haven't don't go looking for it, I may be doing something wrong myself.

**Comment by lukechilds** [comment]
> did you ever at any point stumble on a problem with Maria / MySQL where the JSON would lose all of the backslashes and become un-parseable?

Nope, Keyv specific or MySQL in general?

**Comment by MySidesTheyAreGone** [comment]
I don't know; if it's Keyv it's a separate bug that I may have introduced, we'll see. I'll debug it soon.

**Comment by MySidesTheyAreGone** [comment]
Better title :)

**Comment by MySidesTheyAreGone** [comment]
Thanks!

**Comment by lukechilds** [comment]
No probs, sorry for delay, busy personal life recently.

I'll publish an update to the MySQL adapter today depending on this and explaining usage in the readme.

**Comment by lukechilds** [comment]
@MySidesTheyAreGone Published `@keyv/mysql@1.1.0` 🎉

**Comment by MySidesTheyAreGone** [comment]
Yaaaay!
